import { useState } from 'react'
import { ArrowLeft, HelpCircle, Send } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { Card } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { useAuth } from '@/context/AppContext'
import { useToast } from '@/context/ToastContext'
import api from '@/services/api'
const faqMap: Record<'farmer' | 'consumer' | 'delivery', Array<[string, string]>> = {
  farmer: [['How do I add a product?', 'Open Products, choose Add Product, and enter its price, quantity, and harvest date.'], ['How are certificates reviewed?', 'Upload your certificate from the Certification page. Admin reviews and updates its status.'], ['How do I manage orders?', 'Open Orders to accept, reject, and update each customer order.']],
  consumer: [['How do I place an order?', 'Add products to your cart, select a saved address, then choose Place order.'], ['Can I save multiple addresses?', 'Open Profile, choose Address, and use New address to store another delivery location.'], ['How do I track delivery?', 'Open Orders and select an order to view its current delivery status.']],
  delivery: [['How do I accept a delivery?', 'Open a new delivery order, optionally add a parcel photo, then choose Accept delivery.'], ['Where are my completed deliveries?', 'Open History to view completed deliveries and Earnings to view payment details.'], ['How do I update my vehicle details?', 'Open Profile, choose Vehicle & licence, and save the latest information.']],
}

export default function HelpSupport({ role }: { role: 'farmer' | 'consumer' | 'delivery' }) {
  const navigate = useNavigate(); const { userId, userName, userPhone } = useAuth(); const { toast } = useToast()
  const [name, setName] = useState(userName === 'Guest' ? '' : userName); const [phone, setPhone] = useState(userPhone); const [subject, setSubject] = useState(''); const [description, setDescription] = useState(''); const [sending, setSending] = useState(false); const [error, setError] = useState('')
  const submit = async () => { if (!name.trim() || !phone.trim() || !subject.trim() || !description.trim()) { setError('Name, phone, subject, and description are required.'); return }; setSending(true); setError(''); try { await api.post('/complaints', { user_id: userId ? Number(userId) : null, role, name, phone, subject, description }); toast('Your support request was submitted.', 'success'); setSubject(''); setDescription('') } catch (submitError: any) { setError(submitError?.response?.data?.message || 'Unable to submit your support request right now.') } finally { setSending(false) } }
  return <div className="mx-auto max-w-2xl space-y-5"><Button variant="ghost" size="sm" onClick={() => navigate(`/${role}/profile`)}><ArrowLeft className="h-4 w-4" /> Back to profile</Button><Card><div className="flex items-start gap-3"><div className="rounded-xl bg-primary/10 p-3 text-primary"><HelpCircle className="h-6 w-6" /></div><div><h1 className="text-2xl font-bold font-[family-name:var(--font-display)]">Help & Support</h1><p className="mt-1 text-sm text-muted">Tell us what you need help with.</p></div></div><div className="mt-6 space-y-4"><Input label="Name *" value={name} onChange={(event) => setName(event.target.value)} /><Input label="Phone number *" value={phone} onChange={(event) => setPhone(event.target.value)} /><Input label="Subject *" value={subject} onChange={(event) => setSubject(event.target.value)} placeholder="What can we help with?" /><label className="block text-sm font-medium">Description *<textarea value={description} onChange={(event) => setDescription(event.target.value)} rows={5} placeholder="Describe your issue or question" className="mt-1.5 w-full rounded-2xl border border-border bg-surface-elevated px-4 py-3 text-sm text-foreground placeholder:text-subtle focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/30" /></label>{error && <p className="text-sm text-danger">{error}</p>}<Button onClick={submit} loading={sending}><Send className="h-4 w-4" /> Submit request</Button></div></Card><Card><h2 className="font-semibold">Frequently asked questions</h2><div className="mt-4 space-y-4">{faqMap[role].map(([question, answer]) => <details key={question} className="border-b border-border pb-4 last:border-0"><summary className="cursor-pointer font-medium">{question}</summary><p className="mt-2 text-sm leading-6 text-muted">{answer}</p></details>)}</div></Card></div>
}
